---
- block:
  - name: Remove conflicting older Docker packages from CentOS
    yum:
      name: "{{ docker_ce_CentOS_old_Docker_pkgs }}"
      state: absent

  - name: Add the Docker CE repository on CentOS
    yum_repository:
      name: docker_ce
      description: "YUM repository for Docker Community Edition"
      baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: Install the Docker CE packages on CentOS
    yum:
      name: docker-ce
      state: present
      update_cache: true
  become: true

- name: Install Python control of Docker on CentOS
  pip:
    name: docker
    state: present
    virtualenv: "{{ docker_ce_python_virtualenv }}"
