---
# Consult defaults/main.yml to learn about the role variables.
- block:
  - name: Add the Docker CE repository for YUM
    yum_repository:
      name: docker_ce
      description: "YUM repository for Docker Community Edition"
      baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: Install the Docker CE packages for YUM
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - docker-ce

  - name: Start and enable the Docker daemon
    systemd:
      name: docker
      state: started
      enabled: true
  become: true
